### ISSUE TITLE
Provide Dockerfile

### ISSUE THREAD

**Issue by dmunozv04** [ccf-2012/seedcross#1]
Could you provide a dockerfile so that the project can be built on other architectures (arm)?

**Comment by ccf-2012** [comment]
Sorry for late replay, here's the Dockfile:

`# syntax=docker/dockerfile:1
FROM python:slim
ENV PYTHONUNBUFFERED=1
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . /code/

EXPOSE 8090
ENTRYPOINT ["/code/start.sh"]
`

**Comment by dmunozv04** [comment]
Thank you
