### ISSUE TITLE
TypeError: 'Tracker' object is not subscriptable

### ISSUE THREAD

**Issue by Horridge** [ccf-2012/seedcross#26]
Received the following error when attempting to start Seed Cross. Was working fine, believe the latest docker build introduced this bug.

`Traceback (most recent call last):`
`  File "/usr/local/lib/python3.11/site-packages/background_task/tasks.py", line 43, in bg_runner`
`    func(*args, **kwargs)`
`  File "/code/seedcross/crseed/tasks.py", line 83, in backgroundCrossSeedTask`
`    iterTorrents(dlclient, param, log)`
`  File "/code/seedcross/crseed/CrossSeedAutoDL.py", line 428, in iterTorrents`
`    torList = dlclient.loadTorrents()`
`              ^^^^^^^^^^^^^^^^^^^^^^^`
`  File "/code/seedcross/crseed/torclient.py", line 97, in loadTorrents`
`    st = self.mkSeedTor(trTor)`
`         ^^^^^^^^^^^^^^^^^^^^^`
`  File "/code/seedcross/crseed/torclient.py", line 69, in mkSeedTor`
`    tracker=self.abbrevTracker(trTor.trackers[0]),`
`            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`  File "/code/seedcross/crseed/torclient.py", line 78, in abbrevTracker`
`    trackerJson["announce"]).netloc.split('.')`
`    ~~~~~~~~~~~^^^^^^^^^^^^`
`TypeError: 'Tracker' object is not subscriptable`

**Comment by backbeat99** [comment]
Exact same error for me , using latest docker and transmission as client

**Comment by Horridge** [comment]
Yes, I probably should have added, running Transmission 3.00 (bb6b5a062e)

**Comment by ccf-2012** [comment]
the new transmission-rpc is updated a lot, the new docker and requirements.txt did not fix the package version.

I will try to fix this asap

**Comment by ccf-2012** [comment]
Seems fixed, also docker has updated

**Comment by DanGarion** [comment]
I agree this seems fixed as the error went away after updating and trying this morning.

**Comment by Horridge** [comment]
Have pulled the new image from docker and redeployed; all seems to be working now. Happy to call it fixed!
