### ISSUE TITLE
Feature Request - Add option to skip verify on qbit

### ISSUE THREAD

**Issue by swannie-eire** [ccf-2012/seedcross#3]
Qbittorrent has the option to skip verification.

Currently all torrents are added in a paused state and no check has been carried out which means that you have to remove the torrent and readd it with skip verify to be able to start it.

If you do a recheck of the torrents that are added currently if a file in the torrent is missing such as a NFO then all the torrent data gets moved to incomplete folder(if you have incomplete folder enabled), this means the same torrent from other private trackers fails as it can not find the files to seed. What happens then is that Qbittorrent can start to download the same data at the same time from multiple trackers. 

If skip verification is enabled when adding the torrent it means that if a file such as the NFO is missing it will fail skip verification and the torrent wont start and the torrent data wont be moved so it wont affect the same torrent from other private trackers.

It looks like this is possible with the qbit-api and all that is required for the api call is to add the below and then also add a check box to the UI to enable or disable it.
```
result = self.qbClient.torrents_add(
                    urls=tor_url,
                    is_paused=True,
                    skip_checking=var_skip,
                    save_path=download_location,
                    download_path=download_location )
                if 'OK' in result.upper():
```

https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)

**Comment by ccf-2012** [comment]
I tried and end up with giving up, the reason is:
I can't get the file/folder name before the torrent downloaded, thus I think add `is_skip_checking` option blindly is dangerous.

I have published the faild branch as `skipcheck_fail`

If anyone brave enough,  just check `crseed/CrossSeedAutoDL.py` at about line 465, comment out the name checking before skip checking.
```python 
                if result.title == localTor.name:
                    skipCheck = True
                    s = 'SKIP_CHECK attension, torrent name match: '+ result.title
                    print(s)
                    logger.info(s)
                    log.message(s)
```

besides, such option is available only for qbittorrent, `seed_mode` option in deluge is not tested , and nothing found for transmission.

**Comment by swannie-eire** [comment]
> I tried and end up with giving up, the reason is: I can't get the file/folder name before the torrent downloaded, thus I think add `is_skip_checking` option blindly is dangerous.

I was wondering why the file/folder path the torrents were added to was always wrong and that explains it. 

I'll have a look at the code over the next few days.

**Comment by ccf-2012** [comment]
> Im getting a tonne of DB errors when i run your skip branch e.g missing columns etc..

to run the skip branch:
1. modify the db by using django migration system:
```sh
 python manage.py migrate
```
2. run the 2 command in start.sh

**Comment by swannie-eire** [comment]
> > Im getting a tonne of DB errors when i run your skip branch e.g missing columns etc..
> 
> to run the skip branch:
> 
>     1. modify the db by using django migration system:
> 
> 
> ```shell
>  python manage.py migrate
> ```
> 
>     2. run the 2 command in start.sh

it seems to work now your UI from the skip branch and with my updates in my last comment.

in CrossSeedAutoDL.py update downloadResult function return
```
    return dlclient.addTorrentUrl(result.downloadUrl, localTor.save_path, result.indexer, skipCheck)

```

in torclien for qbt update addTorrentUrl function def to
```
def addTorrentUrl(self, tor_url, download_location, indexer, skip_check=False):
```
and also update with this.
```
                result = self.qbClient.torrents_add(
                    urls=tor_url,
                    is_paused=True,
                    is_skip_checking=skip_check,
                    tags="seedcross," + indexer,
                    autoTMM=False,
                    save_path=download_location,
                    download_path=download_location ) 
```
