### ISSUE TITLE
Feature request - add list of trackers to exclude

### ISSUE THREAD

**Issue by swannie-eire** [ccf-2012/seedcross#8]
I currently have about 100+ trackers in jackett and some of these are public and i dont want to dl torrents from public trackers.

It doesnt look like the response from jackett includes the tracker type e.g private, public etc.. So it doesnt look like it will be possible to have an option to just download torrent from private sites.

Instead of me adding the trackers to use i would prefer the opposite(negate) as i have only a handful of public but have tonnes of private trackers.

**Comment by ccf-2012** [comment]
Is this better way to temporarily disable the public tracker in Jackett/Prawlarr when start crossing?

**Comment by swannie-eire** [comment]
> would it be better way to temporarily disable the public tracker in Jackett/Prawlarr when start crossing?

You would then have to do that every time you run seedcross which is going to be a lot more time consuming than just adding the public trackers once to seedcross

**Comment by swannie-eire** [comment]
it looks like jacket was update to now contain the tracker/indexer type. so all we need is a check box for each type and if checked then search that indexer type.

{
	"FirstSeen": "0001-01-01T00:00:00",
	"Tracker": "EZTV",
	"TrackerId": "eztv",
	"TrackerType": "public",
	"CategoryDesc": "TV",
	"BlackholeLink": null,
	"Title": "go far away S02E13 720p WEBRip x265-MiNX",
	"Guid": "magnet:?xt=urn:btih:24f666b1b3d69ced72daa09cca95f5941e0442cb&dn=go.far.away.S02E13.720p.WEBRip.x265-MiNX%5Beztv%5D.mkv%5Beztv%5D&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A80&tr=udp%3A%2F%2Fglotorrents.pw%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969",
	"Link": null,
	"Details": "https://eztv.re/ep/1545689/go-far-away-s02e13-720p-webrip-x265-minx/",
	"PublishDate": "2020-02-20T12:21:03.3578311+00:00",
	"Category": [5000],
	"Size": 226964272,
	"Files": null,
	"Grabs": null,
	"Description": null,
	"RageID": null,
	"TVDBId": null,
	"Imdb": null,
	"TMDb": null,
	"Author": null,
	"BookTitle": null,
	"Seeders": 0,
	"Peers": 0,
	"Poster": null,
	"InfoHash": "24f666b1b3d69ced72daa09cca95f5941e0442cb",
	"MagnetUri": "magnet:?xt=urn:btih:24f666b1b3d69ced72daa09cca95f5941e0442cb&dn=go.far.away.S02E13.720p.WEBRip.x265-MiNX%5Beztv%5D.mkv%5Beztv%5D&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A80&tr=udp%3A%2F%2Fglotorrents.pw%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969",
	"MinimumRatio": null,
	"MinimumSeedTime": null,
	"DownloadVolumeFactor": 0.0,
	"UploadVolumeFactor": 1.0,
	"Gain": 0.0
}

**Comment by swannie-eire** [comment]
i opened a pull request for this.
